name: Deployment Workflow

on:
  push:
    branches:
      - development

jobs:
  deploy_development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' # Only run this job on the development branch
    timeout-minutes: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Dependencies
        run: npm install
    
      - name: AWS config
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: |
          serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY -o

      - name: Deploy
        run: |
          sls deploy --stage dev



 